### ISSUE TITLE
Rename to js.spec-chai?

### ISSUE THREAD

**Issue by mattbishop** [arichiardi/js-spec-chai#2]
I was initially confused because there's a 'spec-js' project. Easy to mix the direction, but hard to miss the dot. https://www.npmjs.com/package/spec-js

**Comment by arichiardi** [comment]
On August 18, 2017 8:48:36 PM GMT+02:00, Matt Bishop <notifications@github.com> wrote:
>I was initially confused because there's a 'spec-js' project. Easy to
>mix the direction, but hard to miss the dot.
>https://www.npmjs.com/package/spec-js
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/arichiardi/js-spec-chai/issues/2

Uhm I don't like names of folders with dots..let me see if I can make it more visible with tags..if not I will change the name.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mattbishop** [comment]
I guessed as much but this is about naming this lib to exactly match the library it supports.

**Comment by arichiardi** [comment]
You are right about discoverability, you should be able to find it when you write js.spec.

**Comment by mattbishop** [comment]
BTW `js-spec` actually exists too: https://yarnpkg.com/en/package/js-spec

**Comment by arichiardi** [comment]
Thanks for the find, this is the straw that broke the camel's back. I am renaming.
