### ISSUE TITLE
Cannot access `.conform` from Typescript tests

### ISSUE THREAD

**Issue by mattbishop** [arichiardi/js-spec-chai#3]
It looks like the index.d.ts is missing the conform() function defintion. Have a look at this example: 

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/0c635915d4c32f4b33dfda1c1965e10fee8cebb8/types/chai-as-promised/index.d.ts

**Comment by arichiardi** [comment]
Yep I think I need to add that, thanks for spotting it!

**Comment by arichiardi** [comment]
I have checked and they are in `extensions.d.ts`. I see it defined in Visual Studio Code...where is it that you don't see it? Which editor/command fails?

**Comment by mattbishop** [comment]
It wasn't working in Intellij, but then I also discovered it is only attached to `should`. I prefer `expect` so I would use `expect(value).to.not.conform(spec)`

**Comment by mattbishop** [comment]
Actually NM it is in `expect()` after all. I was confusing things.
