### ISSUE TITLE
warning from yarn about dependency

### ISSUE THREAD

**Issue by mattbishop** [arichiardi/js-spec-chai#4]
When I `yarn add` this module to mine, I get this warning in the log:

`warning " > js.spec-chai@0.1.5" has incorrect peer dependency "js.spec@>= 1.0.0 < 2".`

**Comment by arichiardi** [comment]
I have noticed it too, will fix

**Comment by arichiardi** [comment]
I tweaked the `package.json`, but `yarn` still complains. There might be a bug in `yarn`.

**Comment by arichiardi** [comment]
It seems things are in progress regarding `peerDependencies`: https://github.com/yarnpkg/yarn/issues/1503
