### ISSUE TITLE
Declare depencency on js.spec with a hat?

### ISSUE THREAD

**Issue by mattbishop** [arichiardi/js-spec-chai#6]
https://github.com/arichiardi/js.spec-chai/blob/f9a586bd3d3466d99f0b35de4c4bbdd473c6c604/package.json#L41

I wonder if you declared this with a hat, the warning will go away? warning " > js.spec-chai@0.1.6" has incorrect peer dependency "js.spec@>=1.0.0 <2".

**Comment by arichiardi** [comment]
I set only the lower boundary in https://github.com/arichiardi/js.spec-chai/commit/604b22783fd2eb7e800c9065c6b19ddce5d2b5b9.
